#!/bin/bash
# Configuration Check for Production Authentication

echo "=== PRODUCTION AUTHENTICATION CONFIGURATION ==="
echo ""
echo "1. FRONTEND (Vercel) - needs VITE_API_BASE_URL"
echo "   Expected: VITE_API_BASE_URL=https://your-production-api.example.com"
echo "   File: .env.production"
if [ -f .env.production ]; then
    echo "   Current:"
    grep VITE_API_BASE_URL .env.production || echo "   ❌ NOT FOUND"
fi
echo ""
echo "2. BACKEND - needs CORS_ORIGINS"
echo "   Expected: CORS_ORIGINS=https://emploiplus.vercel.app,http://localhost:5173,..."
echo "   Set in: your production host's environment variables (or CI)"
echo ""
echo "3. BACKEND - needs JWT_SECRET and DATABASE_URL"
echo "   Expected: JWT_SECRET=<your-secret>"
echo "   Expected: DATABASE_URL=postgresql://<user>:<pass>@<host>/<db>"
echo "   Set in: your production host's environment variables (or CI)"
echo ""
echo "4. ENDPOINTS TO TEST:"
echo "   POST https://your-production-api.example.com/api/register"
echo "   POST https://your-production-api.example.com/api/login"
echo "   GET  https://your-production-api.example.com/api/users/me (with Bearer token)"
echo ""
echo "5. FRONTEND AUTH FLOW:"
echo "   Files: src/hooks/useAuth.ts, src/pages/LoginUser.tsx, src/pages/Register.tsx"
echo "   Status: ✓ Fixed to use VITE_API_BASE_URL"
echo ""
echo "=== CHECKLIST ==="
echo "[ ] Vercel: VITE_API_BASE_URL env var set to https://your-production-api.example.com"
echo "[ ] Production host: CORS_ORIGINS includes https://emploiplus.vercel.app"
echo "[ ] Production host: JWT_SECRET is set"
echo "[ ] Production host: DATABASE_URL is set to Supabase PostgreSQL"
echo "[ ] Test: Register at https://emploiplus.vercel.app/inscription"
echo "[ ] Test: Login at https://emploiplus.vercel.app/connexion"
echo ""
