#!/bin/bash

# Dashboard Setup & Installation Guide
# This script provides step-by-step instructions for setting up the Dashboard

echo "🎉 SECTION 2: TABLEAU DE BORD - GUIDE D'INSTALLATION"
echo "=================================================="
echo ""
echo "✅ Ce qui a été créé:"
echo ""
echo "Backend:"
echo "  ✓ admin-dashboard-stats.controller.ts - 400+ lignes de logique"
echo "  ✓ admin-dashboard-stats.routes.ts - 3 endpoints API"
echo "  ✓ Intégration dans server.ts"
echo ""
echo "Frontend:"
echo "  ✓ useDashboardStats.ts - Hooks React Query"
echo "  ✓ DashboardCharts.tsx - 5 composants Recharts"
echo "  ✓ AdminDashboardPage.tsx - Page complète avec graphiques"
echo ""
echo "Documentation:"
echo "  ✓ DASHBOARD_COMPLETE_GUIDE.md"
echo "  ✓ DASHBOARD_CODE_EXAMPLES.md"
echo "  ✓ SECTION_2_DASHBOARD_SUMMARY.md"
echo ""
echo "=================================================="
echo ""
echo "📋 ÉTAPES DE VÉRIFICATION:"
echo ""
echo "1️⃣  VÉRIFIER LE BACKEND"
echo "   cd /home/emploiplus-group.com/public_html/backend"
echo "   npm run build"
echo "   npm start"
echo ""
echo "2️⃣  VÉRIFIER LES ROUTES"
echo "   # URL: http://localhost:5000/api/admin/dashboard/stats"
echo "   # Headers: Authorization: Bearer <token>"
echo ""
echo "3️⃣  VÉRIFIER LE FRONTEND"
echo "   cd /home/emploiplus-group.com/public_html/frontend"
echo "   npm run dev"
echo ""
echo "4️⃣  TESTER LE DASHBOARD"
echo "   # Aller à http://localhost:5173/admin"
echo "   # Le tableau de bord doit afficher les graphiques"
echo ""
echo "=================================================="
echo ""
echo "🔑 POINTS CLÉS:"
echo ""
echo "✓ Authentification JWT requise"
echo "✓ Données cachées 5-10 minutes"
echo "✓ Auto-refetch toutes les 30 minutes"
echo "✓ Rate limiting: 120 requêtes/15min"
echo "✓ Gestion d'erreurs complète"
echo "✓ Design responsive"
echo ""
echo "=================================================="
echo ""
echo "🚀 ROUTES API:"
echo ""
echo "GET /api/admin/dashboard/stats"
echo "  → Récupère: totals, applications status, revenue"
echo "  → Cache: 5 minutes"
echo ""
echo "GET /api/admin/dashboard/history"
echo "  → Récupère: 30 jours d'historique"
echo "  → Incluet: users, jobs, applications, formations, revenue"
echo "  → Cache: 10 minutes"
echo ""
echo "GET /api/admin/dashboard/breakdown?category=jobs|applications|users|formations"
echo "  → Récupère: répartition par catégorie"
echo "  → Pour: pie charts"
echo ""
echo "=================================================="
echo ""
echo "📊 GRAPHIQUES INCLUS:"
echo ""
echo "✓ DashboardLineChart - Tendances en ligne"
echo "✓ DashboardAreaChart - Tendances cumulatives"
echo "✓ DashboardBarChart - Comparaisons en barres"
echo "✓ DashboardPieChart - Distributions"
echo "✓ DashboardMultiLineChart - Multi-lignes"
echo ""
echo "=================================================="
echo ""
echo "💾 FICHIERS CRÉÉS:"
echo ""
echo "Backend:"
echo "  /backend/src/controllers/admin-dashboard-stats.controller.ts"
echo "  /backend/src/routes/admin-dashboard-stats.routes.ts"
echo ""
echo "Frontend:"
echo "  /frontend/src/hooks/useDashboardStats.ts"
echo "  /frontend/src/components/admin/charts/DashboardCharts.tsx"
echo "  /frontend/src/components/admin/pages/AdminDashboardPage.tsx"
echo ""
echo "Documentation:"
echo "  /DASHBOARD_COMPLETE_GUIDE.md"
echo "  /DASHBOARD_CODE_EXAMPLES.md"
echo "  /SECTION_2_DASHBOARD_SUMMARY.md"
echo ""
echo "=================================================="
echo ""
echo "⚙️  CONFIGURATION:"
echo ""
echo "Backend (.env):"
echo "  DATABASE_URL=..."
echo "  PORT=5000"
echo "  RATE_LIMIT_WINDOW=15"
echo "  RATE_LIMIT_MAX=120"
echo ""
echo "Frontend (.env):"
echo "  REACT_APP_API_URL=http://localhost:5000/api"
echo ""
echo "=================================================="
echo ""
echo "🧪 TESTER LES ENDPOINTS:"
echo ""
echo "# Avec curl:"
echo "curl -H 'Authorization: Bearer <token>' \\"
echo "  http://localhost:5000/api/admin/dashboard/stats"
echo ""
echo "# Avec fetch:"
echo "fetch('/api/admin/dashboard/stats', {"
echo "  headers: { 'Authorization': 'Bearer <token>' }"
echo "}).then(r => r.json()).then(console.log)"
echo ""
echo "=================================================="
echo ""
echo "✅ PROCHAINES ÉTAPES:"
echo ""
echo "1. Compiler et démarrer le backend"
echo "2. Compiler et démarrer le frontend"
echo "3. Ouvrir http://localhost:5173/admin"
echo "4. Vérifier que le dashboard s'affiche"
echo "5. Vérifier que les graphiques se remplissent"
echo "6. Tester les filtres et rafraîchissements"
echo ""
echo "=================================================="
echo ""
echo "📚 DOCUMENTATION:"
echo ""
echo "Pour plus de détails, consultez:"
echo "  • DASHBOARD_COMPLETE_GUIDE.md - Guide complet"
echo "  • DASHBOARD_CODE_EXAMPLES.md - 10 exemples de code"
echo "  • SECTION_2_DASHBOARD_SUMMARY.md - Résumé"
echo ""
echo "🎉 Installation complète!"
echo ""
